### ISSUE TITLE
Want to use this as a base for next version of Rumonade

### ISSUE THREAD

**Issue by ms-ati** [tcrayford/Values#25]
Hi @tcrayford, thanks for this great library. I like the design choices that you made here.

I'd like to use Values as a basis for a re-writing of the Rumonade gem. However, before doing so there's a series of changes I'd like to propose and discuss with you, before submitting all the PRs:
  1.  [x] Fix zero-field Value class edge case (#23)
  2.  [x] Fix Gemfile.lock issue (#22)
  3.  [x] Add a `#with` method to support hash value replacement (#24)
  4.  [x] Add a `#to_h` method to support conversion to Hash like OpenStruct (#27)
  4.  [x] Add Travis CI and badge (#28)
  5.  [x] Add CodeCov.io and badge (#29, #36 )
  6.  [x] Add gem version badge (#30)
  7.  [x] Document with YARD and add a rubydoc.info link to docs (#38)
  8.  [x] Document that it also replaces OpenStruct (via `#with` and `#to_h`) (#39)
  9.  [x] Release a new major version including all above changes (#40)
  10.  [ ] On supported Ruby versions (2+), use keyword args in `.with` and `#with`
  11.  [ ] Add support for default and required values in `.with`
  12.  [ ] Release a new major version including above features

Thanks again for this library and your time. My only interest in making these changes is to get the library to the point where I can use it as the basis for all immutable types in next version of Rumonade :)

(this issue edited to reflect discussion)

**Comment by ms-ati** [comment]
Ping?

**Comment by ms-ati** [comment]
@tcrayford ping on releasing 1.8.0?

**Comment by tcrayford** [comment]
released!

**Comment by ms-ati** [comment]
:clap:

**Comment by ms-ati** [comment]
@tcrayford :cake: :beer:

**Comment by ms-ati** [comment]
@tcrayford I am going to close this, as I think any support for Ruby 2+ keyword args is a minor change and not worth keeping this issue open.
